### ISSUE TITLE
Investigar sobre el Valor tributario

### ISSUE THREAD

**Issue by balthierStar** [UnlimitedDreams/ProyectoInventarius#29]
> > El IVA general no Existe. (Valor Imptos; Valor Descuentos; Valor Neto; Valor A Pagar).
> > Agregar Campo %IVA Pagado, en Venta_Pro
> > El IVA Existe por producto por producto debe actualizarse.
# Definir Régimen Tributario para todas la empresas
# Organizar la parametrización del pago de aportes sobre empresa
# Ver productos por categoría

**Comment by balthierStar** [comment]
La base de datos ya se ajustó

**Comment by jdcastrillon** [comment]
* facturero. secuencia que da la DIAN
