### ISSUE TITLE
Migración de Operación (Empresa Antigua)

### ISSUE THREAD

**Issue by jdcastrillon** [UnlimitedDreams/ProyectoInventarius#45]
Realizar el estado de apertura y cargar los saldos correspondientes, de las cuentas, y tener en cuenta al menos las siguientes cuentas:

- [ ] Validar estado de la Caja. (1305).
- [ ] Saldo retenido (1355159).
- [ ] IVA a Favor
- [ ] Validar estado de la deuda. (2505)
- [ ] Validar inventario de equipo de Oficina. (151210)
- [ ] Validar inventario de equipo de Operación (134010).
- [ ] Validar inventario de Mercancía no fabricadas por la empresa (1435)
- [ ] Validar inventario de Materias Primas (1405)
- [ ] Validar Producto en Proceso (1410)
- [ ] Validar Producto Terminado (1430)
- [ ] Saldo de Impuestos (24)
- [ ] Validar Saldo de acreedores y Proveedores. (2835- Acreedores // 22 - Proveedores )

La migración debe realizarse con cuidado de no ignorar datos, y debe ser atendida por un especialista de momento, cuando el programa pueda soltar este proceso lo atenderemos.

Cualquier pregunta [REVISA EL PUC](http://puc.com.co/)

**Comment by balthierStar** [comment]
Para este vamos a hacer un balance de P&G
según NIIF, ya tengo como aprender a hacerlo.
