### ISSUE TITLE
Crear configuraciones de implementación inicial

### ISSUE THREAD

**Issue by jdcastrillon** [UnlimitedDreams/ProyectoInventarius#53]
- [ ] Definir entorno de la empresa en la cual se va a trabajar
- [ ] Proceso para realizar el inventario de saldos iniciales para la apertura.
- [ ] Maestro de IVa
- [ ] Configuración de la empresa
- [ ] Proceso de Facturación
- [ ] Información de la BD

**Comment by balthierStar** [comment]
Voy a hacer la configuración de la BD
