### ISSUE TITLE
Políticas de Implementación de NIIF

### ISSUE THREAD

**Issue by jdcastrillon** [UnlimitedDreams/ProyectoInventarius#54]
La implementación aplica para las empresas que ya llevan tiempo de actividad operacional, para ello debe tenerse en cuenta diversos aspectos relacionados con su contabilidad, hay que estar pendiente de cualquier cambio al régimen tributario. 

**Para las nuevas organizaciones no es obligatorio hacer políticas, sin embargo debe saber como se realizar**: las actividades de actualización a NIIF no aplica si no tiene historia.  

## Revisar Wiki

**Comment by balthierStar** [comment]
Conseguí un libro para aprender como se hace! 
- Deberíamos aprender sobre como sacar estados financieros
